version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: library-db
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - library_network

networks:
  library_network:
    driver: bridge
